"""empty message

Revision ID: 475324028736
Revises: e2f65f0a482b
Create Date: 2020-06-12 01:29:58.944879

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '475324028736'
down_revision = 'e2f65f0a482b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comment',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('movie_id', sa.String(length=30), nullable=False),
    sa.Column('comment', sa.String(length=2000), nullable=True),
    sa.Column('date_commented', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['movie_id'], ['movie.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'movie_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('comment')
    # ### end Alembic commands ###
