"""empty message

Revision ID: e2f65f0a482b
Revises: 
Create Date: 2020-05-30 01:04:52.680506

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e2f65f0a482b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lists',
    sa.Column('List_id', sa.Integer(), nullable=False),
    sa.Column('movie_id', sa.String(length=30), nullable=False),
    sa.Column('note', sa.String(length=1000), nullable=True),
    sa.ForeignKeyConstraint(['List_id'], ['list.id'], ),
    sa.ForeignKeyConstraint(['movie_id'], ['movie.id'], ),
    sa.PrimaryKeyConstraint('List_id', 'movie_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('lists')
    # ### end Alembic commands ###
